services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # 현재 host(내 pc)위치 : 이미지 안에 존재하는 위치
    ports:
      - '5432:5432' # 내PC port : 이미지 port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
